application: tsvceo-chrome-device-mgmt
version: 2
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
